on:
  workflow_dispatch:
    branches: main

jobs:
  release:
    name: Perform release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git config user.name 'Cog Bot'
          git config user.email mycoolproject@org.org
          git config --global user.email mycoolproject@org.org
          git config --global user.name 'Cog Bot'

      - name: Cocogitto release
        id: release
        uses: oknozor/cocogitto-action@v3
        with:
          release: true
          git-user: 'Cog Bot'
          git-user-email: 'mycoolproject@org.org'

      - name: Generate Changelog
        run: cog changelog --at ${{ steps.release.outputs.version }} -t full_hash > GITHUB_CHANGELOG.md

      - name: Upload github release
        uses: softprops/action-gh-release@v1
        with:
          body_path: GITHUB_CHANGELOG.md
          tag_name: ${{ steps.release.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
